name: Publish Plugin

on:
  release:
    types: [created]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: fluent-beats/flb-plugin-sdk-action@v1
        with:
          plugin-path: "./code"
          plugin-name: "in_docker_system"

      - name: Upload
        uses: AButler/upload-release-assets@v2.0
        with:
          files: './code/build/flb-in_docker_system.so'
          repo-token: ${{ secrets.GITHUB_TOKEN }}